/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncpayWebhookRouteImport } from './routes/api.public.syncpay-webhook'
import { Route as ApiPublicRemarketingWebhookRouteImport } from './routes/api.public.remarketing-webhook'
import { Route as ApiPublicCreatePixRouteImport } from './routes/api.public.create-pix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncpayWebhookRoute = ApiPublicSyncpayWebhookRouteImport.update({
  id: '/api/public/syncpay-webhook',
  path: '/api/public/syncpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemarketingWebhookRoute =
  ApiPublicRemarketingWebhookRouteImport.update({
    id: '/api/public/remarketing-webhook',
    path: '/api/public/remarketing-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreatePixRoute = ApiPublicCreatePixRouteImport.update({
  id: '/api/public/create-pix',
  path: '/api/public/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/remarketing-webhook': typeof ApiPublicRemarketingWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/remarketing-webhook': typeof ApiPublicRemarketingWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/remarketing-webhook': typeof ApiPublicRemarketingWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/create-pix'
    | '/api/public/remarketing-webhook'
    | '/api/public/syncpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/create-pix'
    | '/api/public/remarketing-webhook'
    | '/api/public/syncpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/create-pix'
    | '/api/public/remarketing-webhook'
    | '/api/public/syncpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCreatePixRoute: typeof ApiPublicCreatePixRoute
  ApiPublicRemarketingWebhookRoute: typeof ApiPublicRemarketingWebhookRoute
  ApiPublicSyncpayWebhookRoute: typeof ApiPublicSyncpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/syncpay-webhook': {
      id: '/api/public/syncpay-webhook'
      path: '/api/public/syncpay-webhook'
      fullPath: '/api/public/syncpay-webhook'
      preLoaderRoute: typeof ApiPublicSyncpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/remarketing-webhook': {
      id: '/api/public/remarketing-webhook'
      path: '/api/public/remarketing-webhook'
      fullPath: '/api/public/remarketing-webhook'
      preLoaderRoute: typeof ApiPublicRemarketingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-pix': {
      id: '/api/public/create-pix'
      path: '/api/public/create-pix'
      fullPath: '/api/public/create-pix'
      preLoaderRoute: typeof ApiPublicCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCreatePixRoute: ApiPublicCreatePixRoute,
  ApiPublicRemarketingWebhookRoute: ApiPublicRemarketingWebhookRoute,
  ApiPublicSyncpayWebhookRoute: ApiPublicSyncpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
